apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: packer-build
spec:
  params:
    - name: packer_build_path
      description: "path to packer build file in the git repo"
      type: string
    #- name: build_config_path
    #  description: "path to build configuration, such as kickstart or answer file"
    #  type: string
  steps:
    - name: build-image
      image: quay.io/vfarias/centos-packer
      resources:
        requests:
          memory: 4Gi
          cpu: 2
          devices.kubevirt.io/kvm: '1'
        limits:
          memory: 8Gi
          cpu: 4
          devices.kubevirt.io/kvm: '1'
      env:
        - name: WORKSPACE
          value: $(workspaces.output.path)
        - name: PACKER_BUILD_PATH
          value: $(params.packer_build_path)
      script: |
        #!/bin/sh
        echo ${WORKSPACE}
        ls -al ${WORKSPACE}
        cd ${WORKSPACE}/$(dirname ${PACKER_BUILD_PATH})
        pwd
        PACKER_LOG=1 /usr/bin/packer build ${WORKSPACE}/${PACKER_BUILD_PATH}
  workspaces:
    - name: output

