---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso-store
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iso-store
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iso-store
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
        imagePullPolicy: Always
        name: iso-store
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: iso-store
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: iso-store
        persistentVolumeClaim:
          claimName: iso-store

---
apiVersion: v1
kind: Service
metadata:
  name: iso-store
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: iso-store

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iso-store
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
