apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: packer-build-
spec:
  taskRef:
    name: packer-build
  params:
    - name: packer_file_path
      value: packer/windows/win2019.pkr.hcl
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: output-image
