apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: packer-build-
spec:
  taskRef:
    name: packer-build
  params:
    - name: buildConfigMapName
      value: win2k19-base
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: pvc-2b32253e66
